title: Aqiqah Berkah
description: Jasa Aqiqah Profesional & Amanah
baseurl: ""
url: "https://zanytemplates.github.io"

markdown: kramdown
theme: null

permalink: /:title/

paginate: 6
paginate_path: "/blog/page:num/"
